name: scan_quest_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.5.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - icons/
    - images/

  fonts:
    - family: Rowdies
      fonts:
        - asset: fonts/Rowdies-Bold.ttf
        - asset: fonts/Rowdies-Light.ttf
        - asset: fonts/Rowdies-Regular.ttf

    - family: SourGummy
      fonts:
        - asset: fonts/SourGummy-Italic-VariableFont_wdth,wght.ttf
        - asset: fonts/SourGummy-VariableFont_wdth,wght.ttf