name: scan_quest_app
description: "A Treasure Hunt App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_p2p_connection: ^2.1.1
  nfc_manager: ^3.5.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - icons/
    - images/

  fonts:
    - family: Rowdies
      fonts:
        - asset: fonts/Rowdies/Rowdies-Bold.ttf
          weight: 900
        - asset: fonts/Rowdies/Rowdies-Light.ttf
        - asset: fonts/Rowdies/Rowdies-Regular.ttf
          style: normal
          weight: 400

    - family: SourGummy
      fonts:
        - asset: fonts/Sour_Gummy/SourGummy-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: fonts/Sour_Gummy/SourGummy-VariableFont_wdth,wght.ttf
          weight: 400